### ISSUE TITLE
Some issues in bash script

### ISSUE THREAD

**Issue by Nithissh0708** [iamthefrogy/nerdbug#2]
![Screenshot_20210628-002134](https://user-images.githubusercontent.com/77142588/123556079-ef0bc100-d7a6-11eb-8a81-11ae6121769e.jpg)

**Comment by Nithissh0708** [comment]
./nerdbug.sh: line 29: warning: here-document at line 1
0 delimited by end-of-file (wanted `enter')ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))
./nerdbug.sh: line 29: warning: here-document at line 2
9 delimited by end-of-file (wanted `enter')ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))
./nerdbug.sh: line 29: syntax error near unexpected tok
en `newline'ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))
./nerdbug.sh: line 29: `echo "Total $(wc -l < domains.t
xtls) new domains found" | notify -telegram -telegram-a
pi-key <<enter api key>> -telegram-chat-id <<enter chat
 id>>'ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))ScreenElement(char= , style=ScreenElementStyle(textColor=null, backColor=null, boldMode=false, underlineMode=false, inverseMode=false, altCharsetMode=false, guardMode=false, newLine=false, fontRGB=null, backRGB=null))

**Comment by iamthefrogy** [comment]
Kindly read the README file before running the script. I have mentioned there, you would need to add your telegram bot ID and API key which seems you haven't added here where it says <enter API key> and <enter chat id>.

So do that and then run the tool. Ensure you have all the tools (dependencies) installed correctly.
